// NOTE: Assertions have been autogenerated by utils/update_mc_test_checks.py UTC_ARGS: --use-same-for-encoding --version 6
// RUN: llvm-mc --triple=riscv32 --mattr=+experimental-zyhybrid --riscv-no-aliases --show-encoding --show-inst < %s \
// RUN:   | FileCheck %s --check-prefixes=CHECK,CHECK-ASM-AND-OBJ
// RUN: llvm-mc --triple=riscv64 --mattr=+experimental-zyhybrid --riscv-no-aliases --show-encoding --show-inst < %s \
// RUN:   | FileCheck %s --check-prefixes=CHECK,CHECK-ASM-AND-OBJ
// RUN: llvm-mc --filetype=obj --triple=riscv32 --mattr=+experimental-zyhybrid --riscv-add-build-attributes < %s \
// RUN:   | llvm-objdump -M no-aliases -d - | FileCheck %s --check-prefixes=CHECK-ASM-AND-OBJ
// RUN: llvm-mc --filetype=obj --triple=riscv64 --mattr=+experimental-zyhybrid --riscv-add-build-attributes < %s \
// RUN:   | llvm-objdump -M no-aliases -d - | FileCheck %s --check-prefixes=CHECK-ASM-AND-OBJ

ymoder a0, a1
// CHECK-ASM-AND-OBJ: ymoder	a0, a1
// CHECK-SAME: # encoding: [0x7b,0x85,0x65,0xf4]
// CHECK-NEXT: # <MCInst #[[#MCINST1:]] YMODER{{$}}
// CHECK-NEXT: #  <MCOperand Reg:X10>
// CHECK-NEXT: #  <MCOperand Reg:X11_Y>>
ymodew a0, a1, a2
// CHECK-ASM-AND-OBJ: ymodew	a0, a1, a2
// CHECK-SAME: # encoding: [0x7b,0x85,0xc5,0x56]
// CHECK-NEXT: # <MCInst #[[#MCINST2:]] YMODEW{{$}}
// CHECK-NEXT: #  <MCOperand Reg:X10_Y>
// CHECK-NEXT: #  <MCOperand Reg:X11_Y>
// CHECK-NEXT: #  <MCOperand Reg:X12>>

/// TODO: ymodesw{i,y} toggles RVI compatibility mode, we should emit .option
/// and amapping symbol to disable RVI compatibility mode so that subsequent
/// instructions are parsed/disassembled correctly.
ymodeswy
// CHECK-ASM-AND-OBJ: ymodeswy
// CHECK-SAME: # encoding: [0x33,0x00,0x00,0x56]
// CHECK-NEXT: # <MCInst #[[#MCINST3:]] YMODESWY>{{$}}
ymodeswi
// CHECK-ASM-AND-OBJ: ymodeswi
// CHECK-SAME: # encoding: [0x33,0x00,0x10,0x56]
// CHECK-NEXT: # <MCInst #[[#MCINST4:]] YMODESWI>{{$}}
