; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
;; A minimal test to check that we can load and store capabilities (in RVI mode)
; RUN: llc < %s -mtriple=riscv32 -mattr=+experimental-y | FileCheck %s
; RUN: llc < %s -mtriple=riscv64 -mattr=+experimental-y | FileCheck %s

define ptr addrspace(200) @load_cap(ptr %p) nounwind {
; CHECK-LABEL: load_cap:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ly a0, 0(a0)
; CHECK-NEXT:    ret
  %ret = load ptr addrspace(200), ptr %p, align 16
  ret ptr addrspace(200) %ret
}

define void @store_cap(ptr %p, ptr addrspace(200) %val) nounwind {
; CHECK-LABEL: store_cap:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sy a1, 0(a0)
; CHECK-NEXT:    ret
  store ptr addrspace(200) %val, ptr %p, align 16
  ret void
}
