; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
;; A minimal test to check that we can pass and return capability arguments in registers
;; Note: passing on-stack arguments is not yet supported.
; RUN: llc < %s -mtriple=riscv32 -mattr=+experimental-y | FileCheck %s
; RUN: llc < %s -mtriple=riscv64 -mattr=+experimental-y | FileCheck %s

define ptr addrspace(200) @return_cap_arg0(ptr addrspace(200) %cap_arg) nounwind {
; CHECK-LABEL: return_cap_arg0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
  ret ptr addrspace(200) %cap_arg
}
define ptr addrspace(200) @return_cap_arg1(i32 %arg0, ptr addrspace(200) %cap_arg) nounwind {
; CHECK-LABEL: return_cap_arg1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ymv a0, a1
; CHECK-NEXT:    ret
  ret ptr addrspace(200) %cap_arg
}
define ptr addrspace(200) @return_cap_arg2(i32 %arg0, i32 %arg1, ptr addrspace(200) %cap_arg) nounwind {
; CHECK-LABEL: return_cap_arg2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ymv a0, a2
; CHECK-NEXT:    ret
  ret ptr addrspace(200) %cap_arg
}
define ptr addrspace(200) @return_cap_arg3(i32 %arg0, i32 %arg1, i32 %arg2, ptr addrspace(200) %cap_arg) nounwind {
; CHECK-LABEL: return_cap_arg3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ymv a0, a3
; CHECK-NEXT:    ret
  ret ptr addrspace(200) %cap_arg
}
define ptr addrspace(200) @return_cap_arg4(i32 %arg0, i32 %arg1, i32 %arg2, i32 %arg3, ptr addrspace(200) %cap_arg) nounwind {
; CHECK-LABEL: return_cap_arg4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ymv a0, a4
; CHECK-NEXT:    ret
  ret ptr addrspace(200) %cap_arg
}
define ptr addrspace(200) @return_cap_arg5(i32 %arg0, i32 %arg1, i32 %arg2, i32 %arg3, i32 %arg4, ptr addrspace(200) %cap_arg) nounwind {
; CHECK-LABEL: return_cap_arg5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ymv a0, a5
; CHECK-NEXT:    ret
  ret ptr addrspace(200) %cap_arg
}
define ptr addrspace(200) @return_cap_arg6(i32 %arg0, i32 %arg1, i32 %arg2, i32 %arg3, i32 %arg4, i32 %arg5, ptr addrspace(200) %cap_arg) nounwind {
; CHECK-LABEL: return_cap_arg6:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ymv a0, a6
; CHECK-NEXT:    ret
  ret ptr addrspace(200) %cap_arg
}
define ptr addrspace(200) @return_cap_arg7(i32 %arg0, i32 %arg1, i32 %arg2, i32 %arg3, i32 %arg4, i32 %arg5, i32 %arg6, ptr addrspace(200) %cap_arg) nounwind {
; CHECK-LABEL: return_cap_arg7:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ymv a0, a7
; CHECK-NEXT:    ret
  ret ptr addrspace(200) %cap_arg
}

define ptr addrspace(200) @call_cap_arg0(ptr addrspace(200) %cap_arg) nounwind {
; CHECK-LABEL: call_cap_arg0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    tail return_cap_arg0
  %ret = tail call ptr addrspace(200) @return_cap_arg0(ptr addrspace(200) %cap_arg)
  ret ptr addrspace(200) %ret
}
define ptr addrspace(200) @call_cap_arg1(ptr addrspace(200) %cap_arg) nounwind {
; CHECK-LABEL: call_cap_arg1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ymv a1, a0
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    tail return_cap_arg1
  %ret = tail call ptr addrspace(200) @return_cap_arg1(i32 0, ptr addrspace(200) %cap_arg)
  ret ptr addrspace(200) %ret
}
define ptr addrspace(200) @call_cap_arg2(ptr addrspace(200) %cap_arg) nounwind {
; CHECK-LABEL: call_cap_arg2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    ymv a2, a0
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    tail return_cap_arg2
  %ret = tail call ptr addrspace(200) @return_cap_arg2(i32 0, i32 1, ptr addrspace(200) %cap_arg)
  ret ptr addrspace(200) %ret
}
define ptr addrspace(200) @call_cap_arg3(ptr addrspace(200) %cap_arg) nounwind {
; CHECK-LABEL: call_cap_arg3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    ymv a3, a0
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    tail return_cap_arg3
  %ret = tail call ptr addrspace(200) @return_cap_arg3(i32 0, i32 1, i32 2, ptr addrspace(200) %cap_arg)
  ret ptr addrspace(200) %ret
}
define ptr addrspace(200) @call_cap_arg4(ptr addrspace(200) %cap_arg) nounwind {
; CHECK-LABEL: call_cap_arg4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    li a3, 3
; CHECK-NEXT:    ymv a4, a0
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    tail return_cap_arg4
  %ret = tail call ptr addrspace(200) @return_cap_arg4(i32 0, i32 1, i32 2, i32 3, ptr addrspace(200) %cap_arg)
  ret ptr addrspace(200) %ret
}
define ptr addrspace(200) @call_cap_arg5(ptr addrspace(200) %cap_arg) nounwind {
; CHECK-LABEL: call_cap_arg5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    li a3, 3
; CHECK-NEXT:    li a4, 4
; CHECK-NEXT:    ymv a5, a0
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    tail return_cap_arg5
  %ret = tail call ptr addrspace(200) @return_cap_arg5(i32 0, i32 1, i32 2, i32 3, i32 4, ptr addrspace(200) %cap_arg)
  ret ptr addrspace(200) %ret
}
define ptr addrspace(200) @call_cap_arg6(ptr addrspace(200) %cap_arg) nounwind {
; CHECK-LABEL: call_cap_arg6:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    li a3, 3
; CHECK-NEXT:    li a4, 4
; CHECK-NEXT:    li a5, 5
; CHECK-NEXT:    ymv a6, a0
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    tail return_cap_arg6
  %ret = tail call ptr addrspace(200) @return_cap_arg6(i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, ptr addrspace(200) %cap_arg)
  ret ptr addrspace(200) %ret
}
define ptr addrspace(200) @call_cap_arg7(ptr addrspace(200) %cap_arg) nounwind {
; CHECK-LABEL: call_cap_arg7:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    li a3, 3
; CHECK-NEXT:    li a4, 4
; CHECK-NEXT:    li a5, 5
; CHECK-NEXT:    li a6, 6
; CHECK-NEXT:    ymv a7, a0
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    tail return_cap_arg7
  %ret = tail call ptr addrspace(200) @return_cap_arg7(i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, ptr addrspace(200) %cap_arg)
  ret ptr addrspace(200) %ret
}
