; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
;; A minimal test to check that we can lower a capability NULL value to a read of register X0_Y
; RUN: llc %s -mtriple=riscv32 -mattr=+experimental-zyhybrid -o -
; RUN: llc < %s -mtriple=riscv32 -mattr=+experimental-zyhybrid | FileCheck %s --check-prefixes=CHECK,CHECK-32
; RUN: llc < %s -mtriple=riscv64 -mattr=+experimental-zyhybrid | FileCheck %s --check-prefixes=CHECK,CHECK-64
; TODO: need to update stack handling to support RVY mode output
; TODO: llc < %s -mtriple=riscv32 -mattr=+experimental-y | FileCheck %s --check-prefixes=CHECK,CHECK-32
; TODO: llc < %s -mtriple=riscv64 -mattr=+experimental-y | FileCheck %s --check-prefixes=CHECK,CHECK-64

declare void @cap_arg(ptr addrspace(200) %val) nounwind
declare void @int_arg(ptr %val) nounwind

define ptr addrspace(200) @return_null() nounwind {
; CHECK-LABEL: return_null:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ymv a0, zero
; CHECK-NEXT:    ret
  ret ptr addrspace(200) null
}

define void @null_arg() nounwind {
; CHECK-32-LABEL: null_arg:
; CHECK-32:       # %bb.0:
; CHECK-32-NEXT:    addi sp, sp, -16
; CHECK-32-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; CHECK-32-NEXT:    li a0, 0
; CHECK-32-NEXT:    call cap_arg
; CHECK-32-NEXT:    li a0, 0
; CHECK-32-NEXT:    call int_arg
; CHECK-32-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; CHECK-32-NEXT:    addi sp, sp, 16
; CHECK-32-NEXT:    ret
;
; CHECK-64-LABEL: null_arg:
; CHECK-64:       # %bb.0:
; CHECK-64-NEXT:    addi sp, sp, -16
; CHECK-64-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; CHECK-64-NEXT:    li a0, 0
; CHECK-64-NEXT:    call cap_arg
; CHECK-64-NEXT:    li a0, 0
; CHECK-64-NEXT:    call int_arg
; CHECK-64-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; CHECK-64-NEXT:    addi sp, sp, 16
; CHECK-64-NEXT:    ret
  call void @cap_arg(ptr addrspace(200) null)
  call void @int_arg(ptr null)
  ret void
}

declare void @cap_vec_arg(<2 x ptr addrspace(200)> %val) nounwind
declare void @int_vec_arg(<2 x ptr> %val) nounwind

define <2 x ptr addrspace(200)> @return_null_vec() nounwind {
; CHECK-LABEL: return_null_vec:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ymv a0, zero
; CHECK-NEXT:    ymv a1, zero
; CHECK-NEXT:    ret
  ret <2 x ptr addrspace(200)> <ptr addrspace(200) null, ptr addrspace(200) null>
}

define void @null_vec_arg() nounwind {
; CHECK-32-LABEL: null_vec_arg:
; CHECK-32:       # %bb.0:
; CHECK-32-NEXT:    addi sp, sp, -16
; CHECK-32-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; CHECK-32-NEXT:    ymv a0, zero
; CHECK-32-NEXT:    ymv a1, zero
; CHECK-32-NEXT:    call cap_vec_arg
; CHECK-32-NEXT:    li a0, 0
; CHECK-32-NEXT:    li a1, 0
; CHECK-32-NEXT:    call int_vec_arg
; CHECK-32-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; CHECK-32-NEXT:    addi sp, sp, 16
; CHECK-32-NEXT:    ret
;
; CHECK-64-LABEL: null_vec_arg:
; CHECK-64:       # %bb.0:
; CHECK-64-NEXT:    addi sp, sp, -16
; CHECK-64-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; CHECK-64-NEXT:    ymv a0, zero
; CHECK-64-NEXT:    ymv a1, zero
; CHECK-64-NEXT:    call cap_arg
; CHECK-64-NEXT:    ymv a0, zero
; CHECK-64-NEXT:    ymv a1, zero
; CHECK-64-NEXT:    call cap_vec_arg
; CHECK-64-NEXT:    li a0, 0
; CHECK-64-NEXT:    li a1, 0
; CHECK-64-NEXT:    call int_vec_arg
; CHECK-64-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; CHECK-64-NEXT:    addi sp, sp, 16
; CHECK-64-NEXT:    ret
  call void @cap_vec_arg(<2 x ptr addrspace(200)> <ptr addrspace(200) null, ptr addrspace(200) null>)
  call void @int_vec_arg(<2 x ptr> <ptr null, ptr null>)
  ret void
}
