; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
;; A minimal test to check that we can take and return capability arguments
; RUN: llc < %s -mtriple=riscv32 -mattr=+experimental-y | FileCheck %s --check-prefixes=CHECK,CHECK32
; RUN: llc < %s -mtriple=riscv64 -mattr=+experimental-y  | FileCheck %s --check-prefixes=CHECK,CHECK64

define ptr addrspace(200) @register_arg7(i32 %arg1, i32 %arg2, i32 %arg3, i32 %arg4, i32 %arg5, i32 %arg6, i32 %arg7, ptr addrspace(200) %cap_arg) nounwind {
; CHECK-LABEL: register_arg7:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ymv a0, a7
; CHECK-NEXT:    ret
  ret ptr addrspace(200) %cap_arg
}

define ptr addrspace(200) @stack_arg0(i32 %arg1, i32 %arg2, i32 %arg3, i32 %arg4, i32 %arg5, i32 %arg6, i32 %arg7, i32 %arg8, ptr addrspace(200) %cap_arg) nounwind {
; CHECK-LABEL: stack_arg0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ly a0, 0(sp)
; CHECK-NEXT:    ret
  ret ptr addrspace(200) %cap_arg
}

define ptr addrspace(200) @stack_arg1(i32 %arg1, i32 %arg2, i32 %arg3, i32 %arg4, i32 %arg5, i32 %arg6, i32 %arg7, i32 %arg8, i32 %stack0, ptr addrspace(200) %cap_arg) nounwind {
; CHECK32-LABEL: stack_arg1:
; CHECK32:       # %bb.0:
; CHECK32-NEXT:    ly a0, 8(sp)
; CHECK32-NEXT:    ret
;
; CHECK64-LABEL: stack_arg1:
; CHECK64:       # %bb.0:
; CHECK64-NEXT:    ly a0, 16(sp)
; CHECK64-NEXT:    ret
  ret ptr addrspace(200) %cap_arg
}

define ptr addrspace(200) @pass_stack_arg0(ptr addrspace(200) %cap_arg) nounwind {
; CHECK32-LABEL: pass_stack_arg0:
; CHECK32:       # %bb.0:
; CHECK32-NEXT:    addi sp, sp, -16
; CHECK32-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; CHECK32-NEXT:    ymv t0, a0
; CHECK32-NEXT:    li a0, 1
; CHECK32-NEXT:    li a1, 2
; CHECK32-NEXT:    li a2, 3
; CHECK32-NEXT:    li a3, 4
; CHECK32-NEXT:    li a4, 5
; CHECK32-NEXT:    li a5, 6
; CHECK32-NEXT:    li a6, 7
; CHECK32-NEXT:    li a7, 8
; CHECK32-NEXT:    sy t0, 0(sp)
; CHECK32-NEXT:    call stack_arg0
; CHECK32-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; CHECK32-NEXT:    addi sp, sp, 16
; CHECK32-NEXT:    ret
;
; CHECK64-LABEL: pass_stack_arg0:
; CHECK64:       # %bb.0:
; CHECK64-NEXT:    addi sp, sp, -32
; CHECK64-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; CHECK64-NEXT:    ymv t0, a0
; CHECK64-NEXT:    li a0, 1
; CHECK64-NEXT:    li a1, 2
; CHECK64-NEXT:    li a2, 3
; CHECK64-NEXT:    li a3, 4
; CHECK64-NEXT:    li a4, 5
; CHECK64-NEXT:    li a5, 6
; CHECK64-NEXT:    li a6, 7
; CHECK64-NEXT:    li a7, 8
; CHECK64-NEXT:    sy t0, 0(sp)
; CHECK64-NEXT:    call stack_arg0
; CHECK64-NEXT:    ld ra, 24(sp) # 8-byte Folded Reload
; CHECK64-NEXT:    addi sp, sp, 32
; CHECK64-NEXT:    ret
  %ret = tail call ptr addrspace(200) @stack_arg0(i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, ptr addrspace(200) %cap_arg)
  ret ptr addrspace(200) %ret
}

define ptr addrspace(200) @pass_stack_arg1(ptr addrspace(200) %cap_arg) nounwind {
; CHECK32-LABEL: pass_stack_arg1:
; CHECK32:       # %bb.0:
; CHECK32-NEXT:    addi sp, sp, -32
; CHECK32-NEXT:    sw ra, 28(sp) # 4-byte Folded Spill
; CHECK32-NEXT:    sy a0, 8(sp)
; CHECK32-NEXT:    li t0, 1
; CHECK32-NEXT:    li a0, 1
; CHECK32-NEXT:    li a1, 2
; CHECK32-NEXT:    li a2, 3
; CHECK32-NEXT:    li a3, 4
; CHECK32-NEXT:    li a4, 5
; CHECK32-NEXT:    li a5, 6
; CHECK32-NEXT:    li a6, 7
; CHECK32-NEXT:    li a7, 8
; CHECK32-NEXT:    sw t0, 0(sp)
; CHECK32-NEXT:    call stack_arg1
; CHECK32-NEXT:    lw ra, 28(sp) # 4-byte Folded Reload
; CHECK32-NEXT:    addi sp, sp, 32
; CHECK32-NEXT:    ret
;
; CHECK64-LABEL: pass_stack_arg1:
; CHECK64:       # %bb.0:
; CHECK64-NEXT:    addi sp, sp, -48
; CHECK64-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; CHECK64-NEXT:    sy a0, 16(sp)
; CHECK64-NEXT:    li t0, 1
; CHECK64-NEXT:    li a0, 1
; CHECK64-NEXT:    li a1, 2
; CHECK64-NEXT:    li a2, 3
; CHECK64-NEXT:    li a3, 4
; CHECK64-NEXT:    li a4, 5
; CHECK64-NEXT:    li a5, 6
; CHECK64-NEXT:    li a6, 7
; CHECK64-NEXT:    li a7, 8
; CHECK64-NEXT:    sd t0, 0(sp)
; CHECK64-NEXT:    call stack_arg1
; CHECK64-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; CHECK64-NEXT:    addi sp, sp, 48
; CHECK64-NEXT:    ret
  %ret = tail call ptr addrspace(200) @stack_arg1(i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 1, ptr addrspace(200) %cap_arg)
  ret ptr addrspace(200) %ret
}
