; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
;; A test to check that we can lower ptradd of capabilities.
; RUN: llc < %s -mtriple=riscv32 -mattr=+experimental-y | FileCheck %s --check-prefixes=CHECK,CHECK-RVY,CHECK-RVY32
; RUN: llc < %s -mtriple=riscv64 -mattr=+experimental-y | FileCheck %s --check-prefixes=CHECK,CHECK-RVY,CHECK-RVY64
;; Finally run the same tests with RVI code generation
; RUN: sed 's/addrspace(200)/addrspace(0)/g' %s | llc -mtriple=riscv32 -mattr=+experimental-y | FileCheck %s --check-prefixes=CHECK,CHECK-RVI,CHECK-RVI32
; RUN: sed 's/addrspace(200)/addrspace(0)/g' %s | llc -mtriple=riscv64 -mattr=+experimental-y | FileCheck %s --check-prefixes=CHECK,CHECK-RVI,CHECK-RVI64

define ptr addrspace(200) @zero_ptradd(ptr addrspace(200) %p) nounwind {
; CHECK-LABEL: zero_ptradd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
  %ret = getelementptr i8, ptr addrspace(200) %p, i32 0
  ret ptr addrspace(200) %ret
}

define ptr addrspace(200) @const_ptradd(ptr addrspace(200) %p) nounwind {
; CHECK-RVY-LABEL: const_ptradd:
; CHECK-RVY:       # %bb.0:
; CHECK-RVY-NEXT:    addiy a0, a0, 1
; CHECK-RVY-NEXT:    ret
;
; CHECK-RVI-LABEL: const_ptradd:
; CHECK-RVI:       # %bb.0:
; CHECK-RVI-NEXT:    addi a0, a0, 1
; CHECK-RVI-NEXT:    ret
  %ret = getelementptr i8, ptr addrspace(200) %p, i32 1
  ret ptr addrspace(200) %ret
}

define ptr addrspace(200) @var_ptradd(ptr addrspace(200) %p, i32 %offset) nounwind {
; CHECK-RVY32-LABEL: var_ptradd:
; CHECK-RVY32:       # %bb.0:
; CHECK-RVY32-NEXT:    addy a0, a0, a1
; CHECK-RVY32-NEXT:    ret
;
; CHECK-RVY64-LABEL: var_ptradd:
; CHECK-RVY64:       # %bb.0:
; CHECK-RVY64-NEXT:    sext.w a1, a1
; CHECK-RVY64-NEXT:    addy a0, a0, a1
; CHECK-RVY64-NEXT:    ret
;
; CHECK-RVI32-LABEL: var_ptradd:
; CHECK-RVI32:       # %bb.0:
; CHECK-RVI32-NEXT:    add a0, a0, a1
; CHECK-RVI32-NEXT:    ret
;
; CHECK-RVI64-LABEL: var_ptradd:
; CHECK-RVI64:       # %bb.0:
; CHECK-RVI64-NEXT:    sext.w a1, a1
; CHECK-RVI64-NEXT:    add a0, a0, a1
; CHECK-RVI64-NEXT:    ret
  %ret = getelementptr i8, ptr addrspace(200) %p, i32 %offset
  ret ptr addrspace(200) %ret
}

;; Test vector cases with scalar and vector base/offset to test all paths
;; through SelectionDAGBuilder::visitGetElementPtr().
define <2 x ptr addrspace(200)> @vec_zero_ptradd_scalar_offset(<2 x ptr addrspace(200)> %p) nounwind {
; CHECK-LABEL: vec_zero_ptradd_scalar_offset:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
  %ret = getelementptr i8, <2 x ptr addrspace(200)> %p, i32 0
  ret <2 x ptr addrspace(200)> %ret
}

define <2 x ptr addrspace(200)> @vec_zero_ptradd_vec_offset(<2 x ptr addrspace(200)> %p) nounwind {
; CHECK-LABEL: vec_zero_ptradd_vec_offset:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
  %ret = getelementptr i8, <2 x ptr addrspace(200)> %p, <2 x i32> <i32 0, i32 0>
  ret <2 x ptr addrspace(200)> %ret
}

define <2 x ptr addrspace(200)> @vec_zero_ptradd_scalar_base(ptr addrspace(200) %p) nounwind {
; CHECK-RVY-LABEL: vec_zero_ptradd_scalar_base:
; CHECK-RVY:       # %bb.0:
; CHECK-RVY-NEXT:    ymv a1, a0
; CHECK-RVY-NEXT:    ret
;
; CHECK-RVI-LABEL: vec_zero_ptradd_scalar_base:
; CHECK-RVI:       # %bb.0:
; CHECK-RVI-NEXT:    mv a1, a0
; CHECK-RVI-NEXT:    ret
  %ret = getelementptr i8, ptr addrspace(200) %p, <2 x i32> <i32 0, i32 0>
  ret <2 x ptr addrspace(200)> %ret
}

define <2 x ptr addrspace(200)> @vec_const_ptradd_scalar_offset(<2 x ptr addrspace(200)> %p) nounwind {
; CHECK-RVY-LABEL: vec_const_ptradd_scalar_offset:
; CHECK-RVY:       # %bb.0:
; CHECK-RVY-NEXT:    addiy a0, a0, 1
; CHECK-RVY-NEXT:    addiy a1, a1, 1
; CHECK-RVY-NEXT:    ret
;
; CHECK-RVI-LABEL: vec_const_ptradd_scalar_offset:
; CHECK-RVI:       # %bb.0:
; CHECK-RVI-NEXT:    addi a0, a0, 1
; CHECK-RVI-NEXT:    addi a1, a1, 1
; CHECK-RVI-NEXT:    ret
  %ret = getelementptr i8, <2 x ptr addrspace(200)> %p, i32 1
  ret <2 x ptr addrspace(200)> %ret
}

define <2 x ptr addrspace(200)> @vec_const_ptradd_vec_offset(<2 x ptr addrspace(200)> %p) nounwind {
; CHECK-RVY-LABEL: vec_const_ptradd_vec_offset:
; CHECK-RVY:       # %bb.0:
; CHECK-RVY-NEXT:    addiy a0, a0, 1
; CHECK-RVY-NEXT:    addiy a1, a1, 2
; CHECK-RVY-NEXT:    ret
;
; CHECK-RVI-LABEL: vec_const_ptradd_vec_offset:
; CHECK-RVI:       # %bb.0:
; CHECK-RVI-NEXT:    addi a0, a0, 1
; CHECK-RVI-NEXT:    addi a1, a1, 2
; CHECK-RVI-NEXT:    ret
  %ret = getelementptr i8, <2 x ptr addrspace(200)> %p, <2 x i32> <i32 1, i32 2>
  ret <2 x ptr addrspace(200)> %ret
}

define <2 x ptr addrspace(200)> @vec_const_ptradd_scalar_base(ptr addrspace(200) %p) nounwind {
; CHECK-RVY-LABEL: vec_const_ptradd_scalar_base:
; CHECK-RVY:       # %bb.0:
; CHECK-RVY-NEXT:    ymv a1, a0
; CHECK-RVY-NEXT:    addiy a0, a0, 1
; CHECK-RVY-NEXT:    addiy a1, a1, 2
; CHECK-RVY-NEXT:    ret
;
; CHECK-RVI-LABEL: vec_const_ptradd_scalar_base:
; CHECK-RVI:       # %bb.0:
; CHECK-RVI-NEXT:    addi a2, a0, 1
; CHECK-RVI-NEXT:    addi a1, a0, 2
; CHECK-RVI-NEXT:    mv a0, a2
; CHECK-RVI-NEXT:    ret
  %ret = getelementptr i8, ptr addrspace(200) %p, <2 x i32> <i32 1, i32 2>
  ret <2 x ptr addrspace(200)> %ret
}

define <2 x ptr addrspace(200)> @vec_var_ptradd_scalar_offset(<2 x ptr addrspace(200)> %p, i32 %offset) nounwind {
; CHECK-RVY32-LABEL: vec_var_ptradd_scalar_offset:
; CHECK-RVY32:       # %bb.0:
; CHECK-RVY32-NEXT:    addy a0, a0, a2
; CHECK-RVY32-NEXT:    addy a1, a1, a2
; CHECK-RVY32-NEXT:    ret
;
; CHECK-RVY64-LABEL: vec_var_ptradd_scalar_offset:
; CHECK-RVY64:       # %bb.0:
; CHECK-RVY64-NEXT:    sext.w a2, a2
; CHECK-RVY64-NEXT:    addy a0, a0, a2
; CHECK-RVY64-NEXT:    addy a1, a1, a2
; CHECK-RVY64-NEXT:    ret
;
; CHECK-RVI32-LABEL: vec_var_ptradd_scalar_offset:
; CHECK-RVI32:       # %bb.0:
; CHECK-RVI32-NEXT:    add a0, a0, a2
; CHECK-RVI32-NEXT:    add a1, a1, a2
; CHECK-RVI32-NEXT:    ret
;
; CHECK-RVI64-LABEL: vec_var_ptradd_scalar_offset:
; CHECK-RVI64:       # %bb.0:
; CHECK-RVI64-NEXT:    sext.w a2, a2
; CHECK-RVI64-NEXT:    add a0, a0, a2
; CHECK-RVI64-NEXT:    add a1, a1, a2
; CHECK-RVI64-NEXT:    ret
  %ret = getelementptr i8, <2 x ptr addrspace(200)> %p, i32 %offset
  ret <2 x ptr addrspace(200)> %ret
}

define <2 x ptr addrspace(200)> @vec_var_ptradd_vec_offset(<2 x ptr addrspace(200)> %p, <2 x i32> %offset) nounwind {
; CHECK-RVY32-LABEL: vec_var_ptradd_vec_offset:
; CHECK-RVY32:       # %bb.0:
; CHECK-RVY32-NEXT:    addy a0, a0, a2
; CHECK-RVY32-NEXT:    addy a1, a1, a3
; CHECK-RVY32-NEXT:    ret
;
; CHECK-RVY64-LABEL: vec_var_ptradd_vec_offset:
; CHECK-RVY64:       # %bb.0:
; CHECK-RVY64-NEXT:    sext.w a2, a2
; CHECK-RVY64-NEXT:    sext.w a3, a3
; CHECK-RVY64-NEXT:    addy a0, a0, a2
; CHECK-RVY64-NEXT:    addy a1, a1, a3
; CHECK-RVY64-NEXT:    ret
;
; CHECK-RVI32-LABEL: vec_var_ptradd_vec_offset:
; CHECK-RVI32:       # %bb.0:
; CHECK-RVI32-NEXT:    add a0, a0, a2
; CHECK-RVI32-NEXT:    add a1, a1, a3
; CHECK-RVI32-NEXT:    ret
;
; CHECK-RVI64-LABEL: vec_var_ptradd_vec_offset:
; CHECK-RVI64:       # %bb.0:
; CHECK-RVI64-NEXT:    sext.w a2, a2
; CHECK-RVI64-NEXT:    sext.w a3, a3
; CHECK-RVI64-NEXT:    add a0, a0, a2
; CHECK-RVI64-NEXT:    add a1, a1, a3
; CHECK-RVI64-NEXT:    ret
  %ret = getelementptr i8, <2 x ptr addrspace(200)> %p, <2 x i32> %offset
  ret <2 x ptr addrspace(200)> %ret
}

define <2 x ptr addrspace(200)> @vec_var_ptradd_scalar_base(ptr addrspace(200) %p, <2 x i32> %offset) nounwind {
; CHECK-RVY32-LABEL: vec_var_ptradd_scalar_base:
; CHECK-RVY32:       # %bb.0:
; CHECK-RVY32-NEXT:    ymv a3, a0
; CHECK-RVY32-NEXT:    addy a0, a0, a1
; CHECK-RVY32-NEXT:    addy a1, a3, a2
; CHECK-RVY32-NEXT:    ret
;
; CHECK-RVY64-LABEL: vec_var_ptradd_scalar_base:
; CHECK-RVY64:       # %bb.0:
; CHECK-RVY64-NEXT:    ymv a3, a0
; CHECK-RVY64-NEXT:    sext.w a1, a1
; CHECK-RVY64-NEXT:    sext.w a2, a2
; CHECK-RVY64-NEXT:    addy a0, a0, a1
; CHECK-RVY64-NEXT:    addy a1, a3, a2
; CHECK-RVY64-NEXT:    ret
;
; CHECK-RVI32-LABEL: vec_var_ptradd_scalar_base:
; CHECK-RVI32:       # %bb.0:
; CHECK-RVI32-NEXT:    add a1, a0, a1
; CHECK-RVI32-NEXT:    add a2, a0, a2
; CHECK-RVI32-NEXT:    mv a0, a1
; CHECK-RVI32-NEXT:    mv a1, a2
; CHECK-RVI32-NEXT:    ret
;
; CHECK-RVI64-LABEL: vec_var_ptradd_scalar_base:
; CHECK-RVI64:       # %bb.0:
; CHECK-RVI64-NEXT:    sext.w a1, a1
; CHECK-RVI64-NEXT:    sext.w a3, a2
; CHECK-RVI64-NEXT:    add a2, a0, a1
; CHECK-RVI64-NEXT:    add a1, a0, a3
; CHECK-RVI64-NEXT:    mv a0, a2
; CHECK-RVI64-NEXT:    ret
  %ret = getelementptr i8, ptr addrspace(200) %p, <2 x i32> %offset
  ret <2 x ptr addrspace(200)> %ret
}


%struct.Inner = type { [64 x i8], i32 }
%struct.S = type { i32, %struct.Inner, i32 }

define ptr addrspace(200) @struct_gep(ptr addrspace(200) %p) nounwind {
; CHECK-RVY-LABEL: struct_gep:
; CHECK-RVY:       # %bb.0:
; CHECK-RVY-NEXT:    addiy a0, a0, 132
; CHECK-RVY-NEXT:    ret
;
; CHECK-RVI-LABEL: struct_gep:
; CHECK-RVI:       # %bb.0:
; CHECK-RVI-NEXT:    addi a0, a0, 132
; CHECK-RVI-NEXT:    ret
  %ret = getelementptr %struct.Inner, ptr addrspace(200) %p, i32 1, i32 1
  ret ptr addrspace(200) %ret
}

define <2 x ptr addrspace(200)> @vec_struct_gep(<2 x ptr addrspace(200)> %p) nounwind {
; CHECK-RVY-LABEL: vec_struct:
; CHECK-RVY:       # %bb.0:
; CHECK-RVY-NEXT:    addiy a0, a0, 132
; CHECK-RVY-NEXT:    addiy a1, a1, 132
; CHECK-RVY-NEXT:    ret
;
; CHECK-RVI-LABEL: vec_struct:
; CHECK-RVI:       # %bb.0:
; CHECK-RVI-NEXT:    addi a0, a0, 132
; CHECK-RVI-NEXT:    addi a1, a1, 132
; CHECK-RVI-NEXT:    ret
  %ret = getelementptr %struct.Inner, <2 x ptr addrspace(200)> %p, i32 1, i32 1
  ret <2 x ptr addrspace(200)> %ret
}
